os:
    - linux
language: node_js
node_js:
    - "10"
dist: bionic
sudo: required
services:
    - xvfb
addons:
    chrome: stable
before_script:
    - export DISPLAY=:99.0
install:
    - npm set progress=false
    - npm install
script:
    - npm run test
