package com.appoutlet.api.model.snapstore

import java.util.Date

data class SnapStoreApplication(
	// TODO: rename these properties and use @JsonProperty annotation do bind jackson serialization
    val anon_download_url: String? = null,
    val apps: List<String>? = null,
    val architecture: List<String>? = null,
    val binary_filesize: Int? = null,
    val channel: String? = null,
    val common_ids: List<String>? = null,
    val confinement: String?,
    val contact: String? = null,
    val content: String? = null,
    val date_published: Date?,
    val deltas: List<String>? = null,
    val description: String?,
    val developer_id: String? = null,
    val developer_name: String,
    val developer_validation: String? = null,
    val download_sha3_384: String? = null,
    val download_sha512: String? = null,
    val download_url: String?,
    val epoch: Int? = null,
    val gated_snap_ids: List<String>? = null,
    val icon_url: String?,
    val last_updated: Date?,
    val license: String?,
    val name: String,
    val origin: String? = null,
    val package_name: String?,
    val private: Boolean? = null,
    val publisher: String? = null,
    val ratings_average: Int? = null,
    val release: List<Int>? = null,
    val revision: Int? = null,
    val screenshot_urls: List<String>?,
    val snap_id: String,
    val summary: String?,
    val support_url: String?,
    val title: String? = null,
    val version: String?,
    val website: String?
)
